### ISSUE TITLE
print linebreak

### ISSUE THREAD

**Issue by ryoishikawa74** [anirudhjoshi/lastpass2keepass#13]
Hi there ... I'm trying to convert an exported file and I'm getting this error:

File "lastpass2keepass.py", line 17
print lineBreak
                  ^
SyntaxError: Missing parentheses in call to 'print'

I'm using Windows, thanks!

**Comment by shaunplee** [comment]
I'm not the author, but I'm pretty sure you're getting the error because you're running the script with Python 3 instead of Python 2.
