### ISSUE TITLE
Cvs error

### ISSUE THREAD

**Issue by sadfrogchan** [anirudhjoshi/lastpass2keepass#7]
Hello!
Thanks for the script! It works fine with some small test files but when I tried it on a database it gives this error

Traceback (most recent call last):
  File "lastpass2keepass.py", line 74, in <module>
    for x in reader:
_csv.Error: newline inside string

Do you perhaps know how to fix it? Thank you!

**Comment by kmantel** [comment]
Are you using windows? You may need to preprocess your exported csv file with dos2unix.
http://stackoverflow.com/a/17315726/3131666
